<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\AutoTrade.Infrastructure\AutoTrade.Infrastructure.csproj" />
    <ProjectReference Include="..\AutoTrade.Application\AutoTrade.Application.csproj" />
    <ProjectReference Include="..\AutoTrade.Domain\AutoTrade.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
